language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - if [ "$TRAVIS_PHP_VERSION" == "5.4" ]; then composer require orchestra/testbench ~2.0.0 --dev; fi
  - composer install --prefer-source --no-interaction --dev

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
